os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"; fi
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/garethr
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/garethr/homebrew-kubeval
script:
  - ./test.sh
