matrix:
  include:
    - os: linux
      sudo: required
      before_install:
          - sudo apt-get update && sudo apt-get install linuxbrew-wrapper -y
          - brew update
          - brew --env
          - brew config
    - os: osx

before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/garethr
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/garethr/homebrew-kubeval
script:
  - ./test.sh
